const swaggerJsdoc = require("swagger-jsdoc");

const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: "Flyt API",
      version: "1.0.0",
      description: "Flyt API with autogenerated swagger doc"
    }
  },
  // List of files to be processes. You can also set globs './routes/*.js'
  apis: ["src/api/server.js"]
};

const specs = swaggerJsdoc(options);
module.exports = specs;
